name: Release_Pipeline_macos
on:
  push:
    branches:
      - master
  schedule:
      - cron: "0 22 * * *"
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute Behave tests
        run: |
          cd features
          behave OrgangeHRMLogin.feature
      - name: Upload Test Resultsm
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults/JunitReports/TESTS-*.xml
